apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: mimiproject
spec:
  replicas: 1
  selector:
    matchLabels:
      project: mimiusers
  template:
    metadata:
      labels:
        project: mimiusers
    spec:
      containers:
        - name: users
          image: daul0519/mimiusers:v.1.3
          resources:

          ports:
            - containerPort: 5679
          env:  # ✅ MySQL 환경변수 추가
            - name: DB_HOST
              value: "mysql-service"  # ✅ MySQL Service 이름
            - name: DB_NAME
              value: "mimi"
            - name: DB_USER
              value: "mytest"
            - name: DB_PASSWORD
              value: "1234"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://10.104.200.22:3306/mimi"

---


apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: mimiproject
spec:
  type: LoadBalancer
  selector:
    project: mimiusers
  ports:
    - port: 5679  # ✅ MySQL 기본 포트
      targetPort: 5679